name: Tox tests

on: [push, pull_request]

jobs:
  py39:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Tox
        run: pip install tox
      - name: Install Poetry
        run: pip install poetry
      - name: Run Tox
        run: tox -e py39
  py313:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install Tox
        run: pip install tox
      - name: Install Poetry
        run: pip install poetry
      - name: Run Tox
        run: tox -e py313
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install Tox
        run: pip install tox
      - name: Install Poetry
        run: pip install poetry
      - name: Run Tox
        run: tox -e static
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install Tox
        run: pip install tox
      - name: Install Poetry
        run: pip install poetry
      - name: Run Tox
        run: tox -e cov
      # Codecov Action required installing pytest-cov as it needs coverage.
      # The coverage library installed within tox is in virt-env and not
      # accessible to Codecov.
      - name: Install pytest cov
        run: pip install pytest-cov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install Tox
        run: pip install tox
      - name: Install Poetry
        run: pip install poetry
      - name: Run Tox
        run: tox -e docs
